// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// The web build exists for checking the app in a browser during
  /// development (MANUAL 42); it isn't published.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19KnXZhT0hxB62gXNMaTV5x-MfWv3R5Q',
    appId: '1:227856433742:web:84b7bd6669ed0d4812391f',
    messagingSenderId: '227856433742',
    projectId: 'incomodo-c161e',
    authDomain: 'incomodo-c161e.firebaseapp.com',
    storageBucket: 'incomodo-c161e.firebasestorage.app',
    measurementId: 'G-Z4YJWKSFPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh6TIOXmcQNdvble0DS-PmZDrjME5QdAs',
    appId: '1:227856433742:android:6ed114cb0c172e5b12391f',
    messagingSenderId: '227856433742',
    projectId: 'incomodo-c161e',
    storageBucket: 'incomodo-c161e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90P22d1HDC3iagK3motUu6Aj5ZqNF1Y8',
    appId: '1:227856433742:ios:fbdc1ca31f3a680c12391f',
    messagingSenderId: '227856433742',
    projectId: 'incomodo-c161e',
    storageBucket: 'incomodo-c161e.firebasestorage.app',
    iosBundleId: 'app.incomodo.incomodo',
  );
}
